export const showBooks = (books) => ({type: 'SHOW_BOOKS', payload: books})
export const sortBooks = (sortBy) => ({type: 'SORT_BOOKS', payload: sortBy})
export const filterBooks = filterBy => ({type: 'FILTER_BOOKS', payload: filterBy})
export const addToCart = item => ({type: 'ADD_TO_CART', payload: item})
export const removeFromCart = item => ({type: 'REMOVE_FROM_CART', payload: item})
export const showCart = () => ({type: 'SHOW_CART'})
export const hideCart = () => ({type: 'HIDE_CART'})