export const showBooks = books => ({type: 'SHOW_BOOKS', payload: books})
export const sortBooks = sortBy => ({type: 'SORT_BOOKS', payload: sortBy})
export const filterBooks = filterBy => ({type: 'FILTER_BOOKS', payload: filterBy})
export const addToCart = id => ({type: 'ADD_TO_CART', payload: id})
export const removeFromCart = item => ({type: 'REMOVE_FROM_CART', payload: item})
export const toggleCart = isCartShown => ({type: 'TOGGLE_CART', payload: isCartShown})
